/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.carrasquilla.vista.planes;

import es.carrasquilla.model.Plane;
import java.util.Date;
import java.util.regex.Pattern;


/**
 *
 * @author Francisco Miguel Carrasquilla Rodríguez-Córdoba
 * <afcarrasquilla@iesfranciscodelosrios.es>
 */
public class AirplaneDetailsPanel extends javax.swing.JPanel {

    private Plane plane;
    private boolean edit; 
    
    public AirplaneDetailsPanel() {
        initComponents();
    }

    public Plane getPlane() {
        return plane;
    }

    public void setPlane(Plane plane) {
        this.plane = plane;
    }

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean edit) {
        this.edit = edit;
        textDate.setEditable(edit);
        textPrice.setEditable(edit);
        textAutonomy.setEditable(edit);
        textConsumption.setEditable(edit);
        textCapacity.setEditable(edit);
    }
    
    public void loadData(){
        if(plane != null){
            textDate.setText(plane.getAcquisitionDate().toString());
            textPrice.setText(Double.toString(plane.getPrice()));
            textAutonomy.setText(Float.toString(plane.getAutonomy()));
            textConsumption.setText(Float.toString(plane.getConsumption()));
            textCapacity.setText(Integer.toString(plane.getCapacity()));
        }else{
            textDate.setText("");
            textPrice.setText("");
            textAutonomy.setText("");
            textConsumption.setText("");
            textCapacity.setText("");
        }
        textDate.requestFocus();
    }
    
    public boolean saveData(){
        boolean flag=false;
        if (plane == null) {
            plane = new Plane();
        }
        String regexp = "^(?:3[01]|[12][0-9]|0?[1-9])([\\-/.])(0?[1-9]|1[1-2])\\1\\d{4}$";
        if (Pattern.matches(regexp, textDate.getText())) {
            plane.setAcquisitionDate((Date)textDate.getValue());
            flag=true;
        }
        plane.setPrice(Double.parseDouble(textPrice.getText()));
        plane.setAutonomy(Float.parseFloat(textAutonomy.getText()));
        plane.setConsumption(Float.parseFloat(textConsumption.getText()));
        plane.setCapacity(Integer.parseInt(textCapacity.getText()));
        return flag;
    }
    
    public boolean checkData(){
        boolean noEmpty = false;
        if (!textDate.getText().equals("") && 
                !textPrice.getText().equals("") &&
                !textAutonomy.getText().equals("") &&
                !textConsumption.getText().equals("") &&
                !textCapacity.getText().equals("")) {
            noEmpty = true;
        }
        return noEmpty;
    }
    

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _acquisitionDate = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        _price = new javax.swing.JLabel();
        _autonomy = new javax.swing.JLabel();
        _consumption = new javax.swing.JLabel();
        _capacity = new javax.swing.JLabel();
        textPrice = new javax.swing.JTextField();
        textDate = new javax.swing.JFormattedTextField();
        textAutonomy = new javax.swing.JTextField();
        textConsumption = new javax.swing.JTextField();
        textCapacity = new javax.swing.JTextField();
        _vehicles = new javax.swing.JLabel();
        textvehicles = new javax.swing.JTextField();

        _acquisitionDate.setText("Fecha adquisición:");

        _price.setText("Precio:");

        _autonomy.setText("Autonomía:");

        _consumption.setText("Consumisión:");

        _capacity.setText("Capacidad:");

        _vehicles.setText("Plazas vehículos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_vehicles)
                        .addGap(18, 18, 18)
                        .addComponent(textvehicles))
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_acquisitionDate)
                            .addComponent(_price)
                            .addComponent(_autonomy)
                            .addComponent(_consumption)
                            .addComponent(_capacity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textDate)
                            .addComponent(textPrice)
                            .addComponent(textAutonomy)
                            .addComponent(textConsumption)
                            .addComponent(textCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_acquisitionDate)
                    .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_price)
                    .addComponent(textPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_autonomy)
                    .addComponent(textAutonomy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_consumption)
                    .addComponent(textConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_capacity)
                    .addComponent(textCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_vehicles)
                    .addComponent(textvehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _acquisitionDate;
    private javax.swing.JLabel _autonomy;
    private javax.swing.JLabel _capacity;
    private javax.swing.JLabel _consumption;
    private javax.swing.JLabel _price;
    private javax.swing.JLabel _vehicles;
    private javax.swing.JTextField textAutonomy;
    private javax.swing.JTextField textCapacity;
    private javax.swing.JTextField textConsumption;
    private javax.swing.JFormattedTextField textDate;
    private javax.swing.JTextField textPrice;
    private javax.swing.JTextField textvehicles;
    private javax.swing.JComboBox<Plane> tipo;
    // End of variables declaration//GEN-END:variables
}

