package es.carrasquilla.model;

/**
 * Aircrew generated by hbm2java
 */
public class Aircrew  implements java.io.Serializable {


     private int idEmployee;
     private Employee employee;

    public Aircrew() {
    }

    public Aircrew(Employee employee) {
       this.employee = employee;
    }
   
    public int getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(int idEmployee) {
        this.idEmployee = idEmployee;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }




}


