package es.carrasquilla.model;
// Generated 09-dic-2019 21:42:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airport generated by hbm2java
 */
public class Airport  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String city;
     private String country;
     private Set flightsForIdAirportExit = new HashSet(0);
     private Set flightsForIdAirportArrival = new HashSet(0);

    public Airport() {
    }

	
    public Airport(String name, String city, String country) {
        this.name = name;
        this.city = city;
        this.country = country;
    }
    public Airport(String name, String city, String country, Set flightsForIdAirportExit, Set flightsForIdAirportArrival) {
       this.name = name;
       this.city = city;
       this.country = country;
       this.flightsForIdAirportExit = flightsForIdAirportExit;
       this.flightsForIdAirportArrival = flightsForIdAirportArrival;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set getFlightsForIdAirportExit() {
        return this.flightsForIdAirportExit;
    }
    
    public void setFlightsForIdAirportExit(Set flightsForIdAirportExit) {
        this.flightsForIdAirportExit = flightsForIdAirportExit;
    }
    public Set getFlightsForIdAirportArrival() {
        return this.flightsForIdAirportArrival;
    }
    
    public void setFlightsForIdAirportArrival(Set flightsForIdAirportArrival) {
        this.flightsForIdAirportArrival = flightsForIdAirportArrival;
    }




}


