package es.carrasquilla.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     protected Integer id;
     protected String name;
     protected String lastname;
     protected String dni;
     protected String nationality;
     protected Date birthdate;
     protected double salary;
     protected int numFlights;
     protected Set flightEmployees = new HashSet(0);

    public Employee() {
    }

	
    public Employee(String name, String lastname, String dni, String nationality, 
            Date birthdate, double salary, int numFlights) {
        this.name = name;
        this.lastname = lastname;
        this.dni = dni;
        this.nationality = nationality;
        this.birthdate = birthdate;
        this.salary = salary;
        this.numFlights = numFlights;
    }
    public Employee(String name, String lastname, String dni, String nationality, 
            Date birthdate, double salary, int numFlights, Set flightEmployees) {
       this.name = name;
       this.lastname = lastname;
       this.dni = dni;
       this.nationality = nationality;
       this.birthdate = birthdate;
       this.salary = salary;
       this.numFlights = numFlights;
       this.flightEmployees = flightEmployees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    public int getNumFlights() {
        return this.numFlights;
    }
    
    public void setNumFlights(int numFlights) {
        this.numFlights = numFlights;
    }
    public Set getFlightEmployees() {
        return this.flightEmployees;
    }
    
    public void setFlightEmployees(Set flightEmployees) {
        this.flightEmployees = flightEmployees;
    }

}


