package es.carrasquilla.model;
// Generated 09-dic-2019 21:42:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FlightPlane generated by hbm2java
 */
public class FlightPlane  implements java.io.Serializable {


     private Integer id;
     private Flight flight;
     private Plane plane;
     private Date date;

    public FlightPlane() {
    }

    public FlightPlane(Flight flight, Plane plane, Date date) {
       this.flight = flight;
       this.plane = plane;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public Plane getPlane() {
        return this.plane;
    }
    
    public void setPlane(Plane plane) {
        this.plane = plane;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


