package es.carrasquilla.model;
// Generated 09-dic-2019 21:42:24 by Hibernate Tools 4.3.1



/**
 * FlightEmployee generated by hbm2java
 */
public class FlightEmployee  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private Flight flight;

    public FlightEmployee() {
    }

    public FlightEmployee(Employee employee, Flight flight) {
       this.employee = employee;
       this.flight = flight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }




}


